---
title: "Spatial Statistics Learning Group"
subtitle: "Spatial prediction<html><div style='float:left'></div><hr color='#324147' size=4px width=800px></html>"
date: "<br/>Week 4: 18 December 2019"
output:
  xaringan::moon_reader:
    css: ["default", "mtheme.css", "fonts_mtheme.css", "my-theme.css"]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
editor_options: 
  chunk_output_type: console
---
```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(cache = T)
```

# Prediction

**.center[.red[The answer to any prediction problem is a probability distribution
]]**
<p align="right">.red[Peter McCullagh]</p>

--

$T=$ any quantity of scientific interest

--

$Y=$ data that can tell us something about $T$

--

The .red[predictive distribution] of $T$ is the conditional probability distribution of $T$ given $Y$

---
# The linear geostatistical model

$$Y_i=\mu(x_i) +S(x_i) + Z_i:i=1,\ldots,n$$


$Y_i$ observation at location $x_i$

$\mu(x_i)=d(x_i)^T\beta$

$d(x_i)$ is a set of spatially indexed covariates



$S(x_i)$ spatial Gaussian process


$Z_i$ uncorrelated $N(0, \tau^2)$

---
# .font90[Geostatistical prediction: a general algorithm]

$Y = \{Y_1,\ldots, Y_n\}$ at locations $x_1, \ldots, x_n$

--

$T(x)=\mu(x) + S(x)$

--

$T^*=\{T(x_1^*),\ldots,T(x_q^*)\}$ with $X^*=\{x_1^*,\ldots,x_q^*\}$ our set of prediction locations

--

<br/>

**Algorithm**

--

- model specifies $[Y, T^*]=[Y\mid T^*][T^*]\rightarrow[T^* \mid Y]$ (Bayes' Theorem)

--

- simulate samples of $T^*$ conditional on $Y$ (.red[predictive distribution])

--

- calculate any property of interest

---
# Prediction for a new location $x^*$

The .red[predictive distribution] $[T^* \mid Y]$ for the linear model is a multivariate Normal

--

The point predictor of $T(x^*)$ is 
$$E[T(x^*)\mid Y = y]=\mu(x^*) + \sigma^2 c(x^*)^T \Sigma^{-1}(y-\mu(x))$$
where
$$c(x^*)=(\rho(||x^*-x_1||;\phi),\ldots,\rho(||x^*-x_n||;\phi))$$

--

Our point predictor can be re-expressed as
$$\hat{T}(x^*)=\mu(x^*)+\sum_{i=1}^{n}w_i(x^*)(Y_i-\mu(x_i))$$

--

The variance of our point predictor is
$$v(x)=Var[T(x^*)\mid Y=y]=\sigma^2(1-\sigma^2c(x^*)^T \Sigma^{-1}c(x^*))$$

--

